version: '3.1'

services:

  db:
    image: postgres:14.1-alpine
    restart: always
    networks:
      - app-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db_files/db_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-database.sh
    ports:
      - "5432:5432"

  adminer:
    image: adminer:latest
    restart: always
    networks:
      - app-network
    ports:
      - "8080:8080"

  app:
    image: node:17.2-alpine3.13
    restart: always
    networks:
      - app-network
    ports:
      - "80:8888"
    volumes:
      - ./api:/home/node/app
    command: [ sh, -c, "cd /home/node/app && npm run dev" ]

networks:
  app-network:
    driver: bridge
