version: '3.1'

services:

  db:
    image: postgres:14.1-alpine
    restart: always
    networks:
      - app-network
    environment:
      POSTGRES_PASSWORD: pwd

  adminer:
    image: adminer:latest
    restart: always
    networks:
      - app-network
    ports:
      - "8080:8080"

  app:
    image: node:17.2-alpine3.13
    restart: always
    networks:
      - app-network
    ports:
      - "80:8888"
    volumes:
      - ./api:/home/node/app
    command: [sh, -c, "cd /home/node/app && npm run dev"]

networks:
  app-network:
    driver: bridge
